name: Update Profile Assets

on:
  schedule:
    - cron: "0 18 * * *" # Once a day at 18:00 UTC
  workflow_dispatch:

concurrency:
  group: update-profile-assets
  cancel-in-progress: true

jobs:
  update-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake Game
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
